device_classes:
  /Server/HP/ILO/ILO4/Scality_ILO:
    devices:
      dc1-ilo-apo4k-s01.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.251.100.201
        name: dc1-ilo-apo4k-s01.fednot.be
        priority: 3
        productionState: -1
      dc1-ilo-apo4k-s02.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.251.100.202
        name: dc1-ilo-apo4k-s02.fednot.be
        priority: 3
        productionState: -1
      dc2-ilo-apo4k-s01.fednot.be:
        collector: DC2
        groups:
        - /Groups/ALL
        ipAddressString: 10.252.100.201
        name: dc2-ilo-apo4k-s01.fednot.be
        priority: 3
        productionState: -1
      dc2-ilo-apo4k-s02.fednot.be:
        collector: DC2
        groups:
        - /Groups/ALL
        ipAddressString: 10.252.100.202
        name: dc2-ilo-apo4k-s02.fednot.be
        priority: 3
        productionState: -1
      dc2-ilo-apo4k-s03.fednot.be:
        collector: DC2
        groups:
        - /Groups/ALL
        ipAddressString: 10.252.100.203
        name: dc2-ilo-apo4k-s03.fednot.be
        priority: 3
        productionState: -1
      dc2-ilo-apo4k-s04.fednot.be:
        collector: DC2
        groups:
        - /Groups/ALL
        ipAddressString: 10.252.100.204
        name: dc2-ilo-apo4k-s04.fednot.be
        priority: 3
        productionState: -1
      dc2-ilo-bck-s01.fednot.be:
        collector: DC2
        groups:
        - /Groups/ALL
        ipAddressString: 10.252.100.205
        name: dc2-ilo-bckk-s01.fednot.be
        priority: 3
        productionState: -1
      dc2-ilo-bck-s02.fednot.be:
        collector: DC2
        groups:
        - /Groups/ALL
        ipAddressString: 10.252.100.206
        name: dc2-ilo-bckk-s02.fednot.be
        priority: 3
        productionState: -1
      dc2-ilo-bck-s03.fednot.be:
        collector: DC2
        groups:
        - /Groups/ALL
        ipAddressString: 10.252.100.207
        name: dc2-ilo-bckk-s03.fednot.be
        priority: 3
        productionState: -1
