device_classes:
  /Server/Microsoft/Windows/domain_pra-data.fednot.be:
    devices:
      pra-archsql-s01.pra-data.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.131.202.5
        name: pra-archsql-s01.pra-data.fednot.be
        priority: 3
        productionState: 1000
        systems:
        - /Systems/Infrastructure/Windows/Corporate
        - /Systems/Infrastructure/Windows/Production/SQL
        - /Systems/Infrastructure/Windows/Updates/NO SCCM
        templates:
        - Device
      pra-archsql-s02.pra-data.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.4.230.11
        name: pra-archsql-s02.pra-data.fednot.be
        priority: 3
        productionState: 400
        systems:
        - /Systems/Infrastructure/Windows/Corporate
        - /Systems/Infrastructure/Windows/Production/SQL
        - /Systems/Infrastructure/Windows/Updates/NO SCCM
        templates:
        - Device
      pra-dc-s11.pra-data.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.131.202.51
        name: pra-dc-s11.pra-data.fednot.be
        priority: 3
        productionState: 1000
        systems:
        - /Systems/Infrastructure/Windows/Corporate
        - /Systems/Infrastructure/Windows/Updates/LOW IMPACT
        templates:
        - Active Directory
        - Device
        zProperties:
          zDeviceTemplates:
          - Device
          - Active Directory
      pra-dc-s12.pra-data.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.131.201.51
        name: pra-dc-s12.pra-data.fednot.be
        priority: 3
        productionState: 1000
        systems:
        - /Systems/Infrastructure/Windows/Corporate
        - /Systems/Infrastructure/Windows/Updates/LOW IMPACT
        templates:
        - Device
        zProperties:
          zWinKDC: 10.131.201.51
      pr-sql-n24.pra-data.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.4.220.24
        name: pr-sql-n24.pra-data.fednot.be
        priority: 3
        productionState: 400
        systems:
        - /Systems/Infrastructure/Windows/Production/SQL
        templates:
        - Device
      pr-ssis-s01.pra-data.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.4.230.151
        name: pr-ssis-s01.pra-data.fednot.be
        priority: 3
        productionState: 400
        systems:
        - /Systems/Infrastructure/Windows/Production/SQL
        templates:
        - Device
      pr-ssis-s02.pra-data.fednot.be:
        collector: DC1
        groups:
        - /Groups/ALL
        ipAddressString: 10.4.230.152
        name: pr-ssis-s02.pra-data.fednot.be
        priority: 3
        productionState: 400
        systems:
        - /Systems/Infrastructure/Windows/Production/SQL
        templates:
        - Device

    name: domain_pra-data.fednot.be
    zProperties:
      zWinKDC: 10.131.202.51,10.131.201.51
      zWinRMPort: '5985'
      zWinRMUser: gen_zenoss@PRA-DATA.fednot.be
      zWinScheme: http
