device_classes:
  /Server/Microsoft/Windows/domain_nan.be/devices/prn-dc-s01.nan.be:
    templates:
      DnsMonitor:
        datasources:
          DnsMonitor:
            cycletime: '300'
            datapoints:
              time:
                description: Perform a DNS forward lookup of the device name and check
                  to see that it resolves to the device's manageIp
                rrdtype: GAUGE
            eventClass: /Status/DNS
            expectedIpAddress: ${dev/manageIp}
            hostname: ${dev/titleOrId}
            timeout: 15
            type: DnsMonitor
        description: Perform a DNS forward lookup of the device name and check to
          see that it resolves to the device's manageIp
        graphs:
          DnsLookupTime:
            graphpoints:
              time:
                description: DnsMonitor_time
                dpName: DnsMonitor_time
                legend: ${graphPoint/id}
            height: 100
        targetPythonClass: Products.ZenModel.Device
        thresholds:
          High_Latency:
            dsnames:
            - DnsMonitor_time
            eventClass: /Status/DNS
            maxval: '100'
            timePeriod: 10 minutes
            type: DurationThreshold
            violationPercentage: 100
  /Server/Microsoft/Windows/domain_nan.be/devices/prn-dc-s02.nan.be:
    templates:
      DnsMonitor:
        datasources:
          DnsMonitor:
            cycletime: '300'
            datapoints:
              time:
                description: Perform a DNS forward lookup of the device name and check
                  to see that it resolves to the device's manageIp
                rrdtype: GAUGE
            eventClass: /Status/DNS
            expectedIpAddress: ${dev/manageIp}
            hostname: ${dev/titleOrId}
            timeout: 15
            type: DnsMonitor
        description: Perform a DNS forward lookup of the device name and check to
          see that it resolves to the device's manageIp
        graphs:
          DnsLookupTime:
            graphpoints:
              time:
                description: DnsMonitor_time
                dpName: DnsMonitor_time
                legend: ${graphPoint/id}
            height: 100
        targetPythonClass: Products.ZenModel.Device
        thresholds:
          High_Latency:
            dsnames:
            - DnsMonitor_time
            eventClass: /Status/DNS
            maxval: '100'
            timePeriod: 10 minutes
            type: DurationThreshold
            violationPercentage: 100
  /Server/Microsoft/Windows/domain_nan.be/devices/prn-dc-s03.nan.be:
    templates:
      DnsMonitor:
        datasources:
          DnsMonitor:
            cycletime: '300'
            datapoints:
              time:
                description: Perform a DNS forward lookup of the device name and check
                  to see that it resolves to the device's manageIp
                rrdtype: GAUGE
            eventClass: /Status/DNS
            expectedIpAddress: ${dev/manageIp}
            hostname: ${dev/titleOrId}
            timeout: 15
            type: DnsMonitor
        description: Perform a DNS forward lookup of the device name and check to
          see that it resolves to the device's manageIp
        graphs:
          DnsLookupTime:
            graphpoints:
              time:
                description: DnsMonitor_time
                dpName: DnsMonitor_time
                legend: ${graphPoint/id}
            height: 100
        targetPythonClass: Products.ZenModel.Device
        thresholds:
          High_Latency:
            dsnames:
            - DnsMonitor_time
            eventClass: /Status/DNS
            maxval: '100'
            timePeriod: 10 minutes
            type: DurationThreshold
            violationPercentage: 100
  /Server/Microsoft/Windows/domain_nan.be/devices/prn-dc-s04.nan.be:
    templates:
      DnsMonitor:
        datasources:
          DnsMonitor:
            cycletime: '300'
            datapoints:
              time:
                description: Perform a DNS forward lookup of the device name and check
                  to see that it resolves to the device's manageIp
                rrdtype: GAUGE
            eventClass: /Status/DNS
            expectedIpAddress: ${dev/manageIp}
            hostname: ${dev/titleOrId}
            timeout: 15
            type: DnsMonitor
        description: Perform a DNS forward lookup of the device name and check to
          see that it resolves to the device's manageIp
        graphs:
          DnsLookupTime:
            graphpoints:
              time:
                description: DnsMonitor_time
                dpName: DnsMonitor_time
                legend: ${graphPoint/id}
            height: 100
        targetPythonClass: Products.ZenModel.Device
        thresholds:
          High_Latency:
            dsnames:
            - DnsMonitor_time
            eventClass: /Status/DNS
            maxval: '100'
            timePeriod: 10 minutes
            type: DurationThreshold
            violationPercentage: 100
